
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bean-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bean-simulation
    spec:
      containers:
        - name: beanhold
          image: 944338264176.dkr.ecr.us-east-1.amazonaws.com/dmf:beanhold
          imagePullPolicy: Always
          env:
          - name: JUMP_SERVICE
            value: "true"
          - name: JUMP_WORKERS
            value: "5"
          - name: BEANHOLD_HOSTNAME
            value: "bean-service"
          - name: BEANHOLD_BIND_HOSTNAME
            value: "0.0.0.0"
          ports:
          - containerPort: 2552
            protocol: TCP