
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bean-remote-simulation
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bean-simulation
    spec:
      containers:
        - name: beanhold
          image: dregistry.d-a-s.com/beanhold
          imagePullPolicy: Always
          env:
          - name: DISTRIBUTED
            value: "true"
          - name: DISTRIBUTED_WORKERS
            value: "5"
          - name: BEANHOLD_HOSTNAME
            value: "bean-service"
          - name: BEANHOLD_BIND_HOSTNAME
            value: "0.0.0.0"
          ports:
          - containerPort: 2552
            protocol: TCP
      imagePullSecrets:
        - name: dmfregistrykey